export default {
	SKIING: {
		parameters: [
			{
				name: "temperature_2m_max",
				min_acceptable_value: -8,
				max_acceptable_value: 3,
				optimal_value: -2,
				weight: 2.0,
			},
			{
				name: "temperature_2m_min",
				min_acceptable_value: -10,
				max_acceptable_value: 5,
				optimal_value: -5,
				weight: 1.5,
			},
			{
				name: "precipitation_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 5,
				optimal_value: 1,
				weight: 1.0,
			},
			{
				name: "snowfall_sum",
				min_acceptable_value: 2,
				max_acceptable_value: 15,
				optimal_value: 7,
				weight: 4.0,
			},
			{
				name: "wind_speed_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 25,
				optimal_value: 8,
				weight: 1.2,
			},
			{
				name: "wind_gusts_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 25,
				optimal_value: 8,
				weight: 0.3,
			},
		],
	},
	SURFING: {
		parameters: [
			{
				name: "temperature_2m_max",
				min_acceptable_value: 20,
				max_acceptable_value: 35,
				optimal_value: 25,
				weight: 2.5,
			},
			{
				name: "temperature_2m_min",
				min_acceptable_value: 15,
				max_acceptable_value: 30,
				optimal_value: 20,
				weight: 1.8,
			},
			{
				name: "precipitation_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 10,
				optimal_value: 0,
				weight: 1.8,
			},
			{
				name: "snowfall_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 5,
				optimal_value: 0,
				weight: 1.2,
			},
			{
				name: "wind_speed_10m_max",
				min_acceptable_value: 5,
				max_acceptable_value: 35,
				optimal_value: 15,
				weight: 2.5,
			},
			{
				name: "wind_gusts_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 30,
				optimal_value: 10,
				weight: 0.2,
			},
		],
	},
	OUTDOOR_SIGHTSEEING: {
		parameters: [
			{
				name: "temperature_2m_max",
				min_acceptable_value: 15,
				max_acceptable_value: 30,
				optimal_value: 22,
				weight: 2.0,
			},
			{
				name: "temperature_2m_min",
				min_acceptable_value: 10,
				max_acceptable_value: 25,
				optimal_value: 18,
				weight: 2.0,
			},
			{
				name: "precipitation_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 10,
				optimal_value: 0,
				weight: 3.0,
			},
			{
				name: "snowfall_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 5,
				optimal_value: 0,
				weight: 1.5,
			},
			{
				name: "wind_speed_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 20,
				optimal_value: 5,
				weight: 1.0,
			},
			{
				name: "wind_gusts_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 20,
				optimal_value: 5,
				weight: 0.5,
			},
		],
	},
	INDOOR_SIGHTSEEING: {
		parameters: [
			{
				name: "temperature_2m_max",
				min_acceptable_value: 15,
				max_acceptable_value: 30,
				optimal_value: 20,
				weight: 1.8,
			},
			{
				name: "temperature_2m_min",
				min_acceptable_value: 10,
				max_acceptable_value: 25,
				optimal_value: 18,
				weight: 1.8,
			},
			{
				name: "precipitation_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 20,
				optimal_value: 10,
				weight: 2.5,
			},
			{
				name: "snowfall_sum",
				min_acceptable_value: 0,
				max_acceptable_value: 10,
				optimal_value: 5,
				weight: 2.0,
			},
			{
				name: "wind_speed_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 30,
				optimal_value: 10,
				weight: 1.5,
			},
			{
				name: "wind_gusts_10m_max",
				min_acceptable_value: 0,
				max_acceptable_value: 30,
				optimal_value: 10,
				weight: 0.4,
			},
		],
	},
};
